package com.example.evav3.model

import java.util.Date
import java.util.UUID // Import UUID

data class ChatMessage(
    val id: String = UUID.randomUUID().toString(), // Add a unique ID, generated by default
    val text: String,
    val isSentByUser: Boolean,
    val timestamp: Date
)